### PR TITLE
war 1069- browser_launch and maximize keyword

### PR DESCRIPTION
**Pull request by Annam16**
browser_launch and browser_maximize keyword grouped together to form a new keyword with maximize='yes' as default.
To test this keyword, please run testcases/selenium_func_tests/generic_tests/tc_browser_launch_url_check.xml from warrior_fnc_tests which is available in "http://rtx-swtl-git.fnc.net.local/projects/WAR/repos/warrior_fnc_tests/pull-requests/22/overview" pull request

### CODE REVIEW

**Comment by Annam16** [comment]
@navvrnd the purpose of this ticket is to launch the browser and maximize it at the same time. So it is designed like launch and maximize the browser. Kindly refer jira ticket for more details

**Comment by Annam16** [comment]
@sanikakulkarni @navvrnd @satyakrish @bjrr 
Working on this pull request.

**Comment by Annam16** [comment]
@sanikakulkarni @navvrnd @bjrr @satyakrish 
Implemented war-1069 as below.
1. Added a separate keyword "browser_launch_and_maximize" with "maximize=yes" as default. User can overwrite it as "no" also. For more details please refer war-1069 in JIRA

**Comment by sanikakulkarni** [comment]
Regression logs attached to the ticket.

**Pull request merged**
