### PR TITLE
bugfix/WAR-1609-new: resolved commit-id not working in label tag

### PR DESCRIPTION
**Pull request by navvrnd**
giving commit id in label tag for warhorn configuration was not working like giving proper branch name. Check giving commit id and warhorn pulls the right files.

### CODE REVIEW

**Comment by kaheichan** [comment]
Hi @brettleehari 
is there any update on this ticket?

**Comment by brettleehari** [comment]
Only Ka's review suffice.

**Comment by navvrnd** [comment]
Hi @kaheichan 
1. It applies to all, using branch name works but commit id fails.
2. attached the log with using label (branch) and commit id in the jira ticket.
Please check and approve.

**Comment by kaheichan** [comment]
Verified that checking out commit using commit id is working with warriorspace
Also verified the attached log

**Pull request merged**
