### PR TITLE
WAR-1337 - PR updated with comments

### PR DESCRIPTION
**Pull request by sanikakulkarni**
The Django can launch like the original katana server
After installing Django, run python katana/katana.py

### CODE REVIEW

**Comment by kaheichan** [comment]
Comments from #99 is addressed here

**Comment by kaheichan** [comment]
This pull request contains change from @keenan35i 's branch

**Comment by kaheichan** [comment]
Launched katana without any problem

**Comment by sanikakulkarni** [comment]
All changes addressed - as commented on https://github.com/warriorframework/warriorframework/pull/99

**Pull request merged**
