### PR TITLE
WAR-1298 : Testdata fields reset to default values

### PR DESCRIPTION
**Pull request by priyaarun23**

### CODE REVIEW

**Comment by keenan35i** [comment]
issues are fixed everything saves as y/n vs yes/no now

**Comment by satyakrish** [comment]
saw an issue while testing that on clicking the test data file it tries to load indefinitely.
Observed in sanika's VM and mine on browsers with a clear cache.

**Comment by kaheichan** [comment]
Got this error when trying to create a new cli data files
`"Error: [ng:areq] http://errors.angularjs.org/1.3.15/ng/areq?p0=newTestDataFileCtrl&p1=not%20aNaNunction%2C%20got%20undefined
R/<@http://localhost:5000/assets/OSS/angular/angular.min.js:6:417
Rb@http://localhost:5000/assets/OSS/angular/angular.min.js:19:510
sb@http://localhost:5000/assets/OSS/angular/angular.min.js:20:78
Fe/this.$get</<@http://localhost:5000/assets/OSS/angular/angular.min.js:75:396
link@http://localhost:5000/assets/OSS/angular/angular-route.min.js:7:268
$@http://localhost:5000/assets/OSS/angular/angular.min.js:70:197
B@http://localhost:5000/assets/OSS/angular/angular.min.js:59:255
g@http://localhost:5000/assets/OSS/angular/angular.min.js:51:335
D/<@http://localhost:5000/assets/OSS/angular/angular.min.js:50:444
P/<@http://localhost:5000/assets/OSS/angular/angular.min.js:52:322
k@http://localhost:5000/assets/OSS/angular/angular.min.js:56:322
x@http://localhost:5000/assets/OSS/angular/angular-route.min.js:6:364
$broadcast@http://localhost:5000/assets/OSS/angular/angular.min.js:128:355
n/<@http://localhost:5000/assets/OSS/angular/angular-route.min.js:11:426
f/<@http://localhost:5000/assets/OSS/angular/angular.min.js:112:113
$eval@http://localhost:5000/assets/OSS/angular/angular.min.js:126:11
$digest@http://localhost:5000/assets/OSS/angular/angular.min.js:123:98
$apply@http://localhost:5000/assets/OSS/angular/angular.min.js:126:291
l@http://localhost:5000/assets/OSS/angular/angular.min.js:81:238
M@http://localhost:5000/assets/OSS/angular/angular.min.js:85:342
wf/</F.onload@http://localhost:5000/assets/OSS/angular/angular.min.js:86:367
"  angular.min.js:102:325`

**Comment by sanikakulkarni** [comment]
Closing this PR because this https://github.com/warriorframework/warriorframework/pull/82 is a duplicate

**Pull request closed without merging**
